import { useState, useEffect, useCallback, type KeyboardEvent } from "react";
import { executeDevSql, isDevBuild } from "../../lib/api";
import { DataTable } from "../chat/DataTable";

const IS_DEV = isDevBuild();

interface SqlRunnerProps {
  lastGeneratedSql?: string | null;
  activeSql?: string | null;
}

export function SqlRunner({ lastGeneratedSql, activeSql }: SqlRunnerProps) {
  const [sql, setSql] = useState<string>(activeSql || lastGeneratedSql || "SELECT 1;");
  const [isExecuting, setIsExecuting] = useState(false);
  const [rows, setRows] = useState<Record<string, unknown>[] | null>(null);
  const [latencyMs, setLatencyMs] = useState<number | null>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  // Sync if activeSql changes externally (e.g., when user clicks "RUNNER" on a SQL block)
  useEffect(() => {
    if (activeSql) {
      setSql(activeSql);
    }
  }, [activeSql]);

  const handleRun = useCallback(async () => {
    const trimmed = sql.trim();
    if (!trimmed || isExecuting) return;

    setIsExecuting(true);
    setErrorMsg(null);

    const res = await executeDevSql(trimmed);
    setIsExecuting(false);

    if (res.success) {
      setRows(res.rows || []);
      setLatencyMs(res.dbLatencyMs ?? null);
    } else {
      setErrorMsg(res.error || "Query execution failed");
      setRows(null);
    }
  }, [sql, isExecuting]);

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
      e.preventDefault();
      handleRun();
    }
  };

  const handleLoadLastGenerated = () => {
    if (lastGeneratedSql) {
      setSql(lastGeneratedSql);
    }
  };

  const handleClear = () => {
    setSql("");
    setRows(null);
    setErrorMsg(null);
    setLatencyMs(null);
  };

  if (!IS_DEV) {
    return (
      <div className="sql-runner-container">
        <div className="sql-runner-header">
          <div className="sql-runner-header-title">
            <span className="status-indicator-dot" />
            <span className="sql-runner-title-text">SQL RUNNER (DEV-ONLY)</span>
          </div>
        </div>
        <div className="sql-runner-placeholder">
          <p>
            SQL execution is available in <code>vite dev</code> only
            (via <code>/api/dev-execute-sql</code> middleware). This production
            build has no database proxy — copy generated SQL and run it in your
            own client.
          </p>
          {lastGeneratedSql && (
            <pre className="json-pre">{lastGeneratedSql}</pre>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="sql-runner-container">
      <div className="sql-runner-header">
        <div className="sql-runner-header-title">
          <span className="status-indicator-dot dot-active" />
          <span className="sql-runner-title-text">DEV DB RUNNER</span>
        </div>
        <div className="sql-runner-header-tools">
          {lastGeneratedSql && (
            <button
              type="button"
              className="sql-runner-tool-btn"
              onClick={handleLoadLastGenerated}
              title="Load the most recent SQL generated by the AI agent"
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              <span>LOAD AI SQL</span>
            </button>
          )}
          <button
            type="button"
            className="sql-runner-tool-btn"
            onClick={handleClear}
            title="Clear query and results"
          >
            <span>CLEAR</span>
          </button>
        </div>
      </div>

      <div className="sql-runner-editor-wrap">
        <textarea
          className="sql-runner-textarea"
          value={sql}
          onChange={(e) => setSql(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Write SQL SELECT or WITH query here..."
          rows={6}
          spellCheck={false}
        />
        <div className="sql-runner-editor-footer">
          <span className="sql-runner-hint">
            <kbd className="meta-kbd">Ctrl</kbd> + <kbd className="meta-kbd">Enter</kbd> to run
          </span>
          <span className="sql-runner-guardrail-tag">READ-ONLY: SELECT / WITH</span>
        </div>
      </div>

      <div className="sql-runner-actions-bar">
        <button
          type="button"
          className="btn-sql-runner-execute"
          onClick={handleRun}
          disabled={isExecuting || !sql.trim()}
        >
          {isExecuting ? (
            <>
              <span className="sql-spinner" />
              <span>EXECUTING...</span>
            </>
          ) : (
            <>
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                <polygon points="5 3 19 12 5 21 5 3" />
              </svg>
              <span>RUN QUERY</span>
            </>
          )}
        </button>

        {latencyMs != null && (
          <div className="sql-runner-stats">
            <span className="stat-pill">{latencyMs}ms</span>
            {rows && (
              <span className="stat-pill">
                {rows.length} {rows.length === 1 ? "record" : "records"}
              </span>
            )}
          </div>
        )}
      </div>

      <div className="sql-runner-output-wrap">
        {errorMsg && (
          <div className="sql-runner-error-box">
            <div className="sql-error-header">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="12" cy="12" r="10" />
                <line x1="15" y1="9" x2="9" y2="15" />
                <line x1="9" y1="9" x2="15" y2="15" />
              </svg>
              <strong>Execution Error:</strong>
            </div>
            <div className="sql-error-msg">{errorMsg}</div>
          </div>
        )}

        {rows && rows.length > 0 && (
          <div className="sql-runner-table-container">
            <DataTable rows={rows} />
          </div>
        )}

        {rows && rows.length === 0 && !errorMsg && (
          <div className="sql-runner-empty-result">
            Query executed successfully. 0 records returned.
          </div>
        )}

        {!rows && !errorMsg && !isExecuting && (
          <div className="sql-runner-placeholder">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
              <ellipse cx="12" cy="5" rx="9" ry="3" />
              <path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3" />
              <path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5" />
            </svg>
            <p>Run a query above to see dev database records and performance metrics.</p>
          </div>
        )}
      </div>
    </div>
  );
}
